export const existingRecords = [
	['Centralia', 'Washington', '18629'],
	['Anacortes', 'Washington', '17832'],
	['Aberdeen', 'Washington', '17191'],
	['Washougal', 'Washington', '16970'],
	['West Richland', 'Washington', '16951'],
	['Sunnyside', 'Washington', '16346'],
	['Lynden', 'Washington', '16048'],
	['Port Orchard', 'Washington', '15979'],
	['Ferndale', 'Washington', '15476'],
	['East Wenatchee', 'Washington', '14236'],
	['Snoqualmie', 'Washington', '13810'],
	['Woodinville', 'Washington', '13425'],
	['Lake Forest Park', 'Washington', '13358'],
	['Cheney', 'Washington', '13087'],
	['Newcastle', 'Washington', '12969'],
	['Enumclaw', 'Washington', '12733'],
	['Kelso', 'Washington', '12719'],
	['Edgewood', 'Washington', '12665'],
	['Liberty Lake', 'Washington', '12534'],
	['Ridgefield', 'Washington', '12514'],
	['Sedro-Woolley', 'Washington', '12509'],
	['Gig Harbor', 'Washington', '12181'],
	['Poulsbo', 'Washington', '11891'],
	['Fife', 'Washington', '10985'],
	['Grandview', 'Washington', '10891'],
	['Shelton', 'Washington', '10763'],
	['Yelm', 'Washington', '10707'],
	['Sumner', 'Washington', '10673'],
	['Airway Heights', 'Washington', '10630'],
	['Port Townsend', 'Washington', '10306'],
	['Snohomish', 'Washington', '10154'],
	['DuPont', 'Washington', '10112'],
	['College Place', 'Washington', '9885'],
	['Burlington', 'Washington', '9702'],
	['Orting', 'Washington', '8965'],
	['Milton', 'Washington', '8907'],
	['Hoquiam', 'Washington', '8860'],
	['Toppenish', 'Washington', '8774'],
	['Othello', 'Washington', '8739'],
	['Ephrata', 'Washington', '8477'],
	['Stanwood', 'Washington', '8438'],
	['West Virginia', 'West Virginia', '1782959'],
	['Charleston', 'West Virginia', '48018'],
	['Huntington', 'West Virginia', '46025'],
	['Parkersburg', 'West Virginia', '29403'],
	['Morgantown', 'West Virginia', '29219'],
	['Wheeling', 'West Virginia', '26568'],
	['Martinsburg', 'West Virginia', '18835'],
	['Weirton', 'West Virginia', '18813'],
	['Fairmont', 'West Virginia', '18209'],
	['Beckley', 'West Virginia', '17024'],
	['Clarksburg', 'West Virginia', '15784'],
	['South Charleston', 'West Virginia', '13352'],
	['St. Albans', 'West Virginia', '10635'],
	['Vienna', 'West Virginia', '10576'],
	['Bluefield', 'West Virginia', '9499'],
	['Bridgeport', 'West Virginia', '9257'],
	['Oak Hill', 'West Virginia', '8040'],
	['Moundsville', 'West Virginia', '7981'],
	['Dunbar', 'West Virginia', '7330'],
	['Hurricane', 'West Virginia', '6919'],
	['Elkins', 'West Virginia', '6895'],
	['Charles Town', 'West Virginia', '6523'],
	['Nitro', 'West Virginia', '6518'],
	['Princeton', 'West Virginia', '5798'],
	['Ranson corporation', 'West Virginia', '5726'],
	['Buckhannon', 'West Virginia', '5265'],
	['New Martinsville', 'West Virginia', '5174'],
	['Keyser', 'West Virginia', '4860'],
	['Grafton', 'West Virginia', '4651'],
	['Barboursville village', 'West Virginia', '4291'],
	['Westover', 'West Virginia', '4075'],
	['Point Pleasant', 'West Virginia', '4031'],
	['Weston', 'West Virginia', '3890'],
	['Lewisburg', 'West Virginia', '3868'],
	['Ravenswood', 'West Virginia', '3847'],
	['Pleasant Valley', 'West Virginia', '3492'],
	['Summersville', 'West Virginia', '3408'],
	['Kingwood', 'West Virginia', '3090'],
	['Ripley', 'West Virginia', '3064'],
	['Williamstown', 'West Virginia', '2982'],
	['Kenova', 'West Virginia', '2978'],
	['Williamson', 'West Virginia', '2968'],
	['Philippi', 'West Virginia', '2922'],
	['Fayetteville', 'West Virginia', '2844'],
	['Madison', 'West Virginia', '2838'],
	['Milton', 'West Virginia', '2809'],
	['Follansbee', 'West Virginia', '2799'],
	['Bethlehem village', 'West Virginia', '2558'],
	['Moorefield', 'West Virginia', '2487'],
	['Paden City', 'West Virginia', '2478'],
	['Wellsburg', 'West Virginia', '2401'],
	['Winfield', 'West Virginia', '2390'],
	['Shinnston', 'West Virginia', '2306'],
	['Petersburg', 'West Virginia', '2253'],
	['Hinton', 'West Virginia', '2243'],
	['White Sulphur Springs', 'West Virginia', '2198'],
	['Chester', 'West Virginia', '2173'],
	['Spencer', 'West Virginia', '2038'],
	['Mannington', 'West Virginia', '1946'],
	['Welch', 'West Virginia', '1914'],
	['St. Marys', 'West Virginia', '1830'],
	['Star City', 'West Virginia', '1817'],
	['Belington', 'West Virginia', '1803'],
	['Stonewood', 'West Virginia', '1789'],
	['Romney', 'West Virginia', '1717'],
	['McMechen', 'West Virginia', '1680'],
	['Harrisville', 'West Virginia', '1642'],
	['Richwood', 'West Virginia', '1637'],
	['Ronceverte', 'West Virginia', '1559'],
	['West Liberty', 'West Virginia', '1548'],
	['Eleanor', 'West Virginia', '1539'],
	['Terra Alta', 'West Virginia', '1498'],
	['Shepherdstown', 'West Virginia', '1494'],
	['Glen Dale', 'West Virginia', '1486'],
	['Nutter Fort', 'West Virginia', '1478'],
	['Marmet', 'West Virginia', '1473'],
	['Salem', 'West Virginia', '1470'],
	['New Haven', 'West Virginia', '1462'],
	['Mullens', 'West Virginia', '1445'],
	['Oceana', 'West Virginia', '1441'],
	['Wayne', 'West Virginia', '1423'],
	['Logan', 'West Virginia', '1400'],
	['Ceredo', 'West Virginia', '1393'],
	['Granville', 'West Virginia', '1390'],
	['Sistersville', 'West Virginia', '1381'],
	['Chesapeake', 'West Virginia', '1313'],
	['Mabscott', 'West Virginia', '1313'],
	['Parsons', 'West Virginia', '1307'],
	['Ansted', 'West Virginia', '1290'],
	['Montgomery', 'West Virginia', '1257'],
	['Benwood', 'West Virginia', '1245'],
	['Buffalo', 'West Virginia', '1208'],
	['Barrackville', 'West Virginia', '1206'],
	['Rainelle', 'West Virginia', '1191'],
	['Belle', 'West Virginia', '1146'],
	['Glenville', 'West Virginia', '1112'],
	['Sophia', 'West Virginia', '1107'],
	['Mount Hope', 'West Virginia', '1104'],
	['Pennsboro', 'West Virginia', '1040'],
	['Bolivar', 'West Virginia', '1033'],
	['Milwaukee', 'Wisconsin', '569330'],
	['Madison', 'Wisconsin', '269196'],
	['Green Bay', 'Wisconsin', '107015'],
	['Kenosha', 'Wisconsin', '99286'],
	['Racine', 'Wisconsin', '77127'],
	['Appleton', 'Wisconsin', '74854'],
	['Waukesha', 'Wisconsin', '71256'],
	['Eau Claire', 'Wisconsin', '69441'],
	['Oshkosh', 'Wisconsin', '66607'],
	['Janesville', 'Wisconsin', '65942'],
	['West Allis', 'Wisconsin', '59484'],
	['La Crosse', 'Wisconsin', '52185'],
	['Sheboygan', 'Wisconsin', '49931'],
	['Wauwatosa', 'Wisconsin', '47752'],
	['Fond du Lac', 'Wisconsin', '44595'],
	['Brookfield', 'Wisconsin', '41464'],
	['New Berlin', 'Wisconsin', '40375'],
	['Wausau', 'Wisconsin', '39575'],
	['Menomonee Falls village', 'Wisconsin', '38906'],
	['Greenfield', 'Wisconsin', '37352'],
	['Franklin', 'Wisconsin', '36624'],
	['Beloit', 'Wisconsin', '36609'],
	['Oak Creek', 'Wisconsin', '36260'],
	['Sun Prairie', 'Wisconsin', '36189'],
	['Manitowoc', 'Wisconsin', '34547'],
	['West Bend', 'Wisconsin', '31727'],
	['Fitchburg', 'Wisconsin', '30674'],
	['Mount Pleasant village', 'Wisconsin', '27646'],
	['Neenah', 'Wisconsin', '27525'],
	['Superior', 'Wisconsin', '26561'],
	['Stevens Point', 'Wisconsin', '25692'],
	['De Pere', 'Wisconsin', '25335'],
	['Muskego', 'Wisconsin', '25242'],
	['Caledonia village', 'Wisconsin', '25229'],
	['Mequon', 'Wisconsin', '25200'],
	['Grand Chute', 'Wisconsin', '23876'],
	['Watertown', 'Wisconsin', '22885'],
	['Middleton', 'Wisconsin', '22636'],
	['Pleasant Prairie village', 'Wisconsin', '21392'],
	['Germantown village', 'Wisconsin', '20914'],
	['South Milwaukee', 'Wisconsin', '20517'],
	['Howard village', 'Wisconsin', '20229'],
	['Fox Crossing village', 'Wisconsin', '18925'],
	['Onalaska', 'Wisconsin', '18824'],
	['Marshfield', 'Wisconsin', '18815'],
	['Wisconsin Rapids', 'Wisconsin', '18738'],
	['Oconomowoc', 'Wisconsin', '18379'],
	['Menasha', 'Wisconsin', '18107'],
	['Cudahy', 'Wisconsin', '17946'],
	['Kaukauna', 'Wisconsin', '17170'],
	['Ashwaubenon village', 'Wisconsin', '16913'],
	['Menomonie', 'Wisconsin', '16794'],
	['Beaver Dam', 'Wisconsin', '16647'],
	['River Falls', 'Wisconsin', '16618'],
	['Bellevue village', 'Wisconsin', '16122'],
	['Pewaukee', 'Wisconsin', '15945'],
	['Hartford', 'Wisconsin', '15747'],
	['Weston village', 'Wisconsin', '15688'],
	['Hudson', 'Wisconsin', '15149'],
	['Waunakee village', 'Wisconsin', '14950'],
	['Chippewa Falls', 'Wisconsin', '14778'],
	['Whitefish Bay village', 'Wisconsin', '14747'],
	['Greendale village', 'Wisconsin', '14652'],
	['Salem Lakes village', 'Wisconsin', '14614'],
	['Whitewater', 'Wisconsin', '14351'],
	['Verona', 'Wisconsin', '14276'],
	['Allouez village', 'Wisconsin', '14004'],
	['Plover village', 'Wisconsin', '13701'],
	['Shorewood village', 'Wisconsin', '13648'],
	['Harrison village', 'Wisconsin', '13179'],
	['Glendale', 'Wisconsin', '13178'],
	['Stoughton', 'Wisconsin', '13085'],
	['Suamico village', 'Wisconsin', '13078'],
	['Greenville', 'Wisconsin', '12964'],
	['Brown Deer village', 'Wisconsin', '12705'],
	['Port Washington', 'Wisconsin', '12614'],
	['Fort Atkinson', 'Wisconsin', '12489'],
	['Cedarburg', 'Wisconsin', '12400'],
	['Baraboo', 'Wisconsin', '12398'],
	['Grafton village', 'Wisconsin', '12298'],
	['Little Chute village', 'Wisconsin', '12170'],
	['Richfield village', 'Wisconsin', '11810'],
	['Platteville', 'Wisconsin', '11764'],
	['Sussex village', 'Wisconsin', '11597'],
	['Waupun', 'Wisconsin', '11515'],
	['Oregon village', 'Wisconsin', '11407'],
	['Two Rivers', 'Wisconsin', '11270'],
	['Marinette', 'Wisconsin', '11048'],
	['Burlington', 'Wisconsin', '11008'],
	['Holmen village', 'Wisconsin', '10896'],
	['DeForest village', 'Wisconsin', '10884'],
	['Lisbon', 'Wisconsin', '10561'],
	['Monroe', 'Wisconsin', '10537'],
	['Hobart village', 'Wisconsin', '10351'],
	['New Richmond', 'Wisconsin', '10350'],
	['Elkhorn', 'Wisconsin', '10330'],
	['Portage', 'Wisconsin', '10327'],
	['Reedsburg', 'Wisconsin', '10043'],
	['Sparta', 'Wisconsin', '9972'],
	['Sturgeon Bay', 'Wisconsin', '9706'],
	['Wyoming', 'Wyoming', '578803'],
	['Cheyenne', 'Wyoming', '65051'],
	['Casper', 'Wyoming', '58656'],
	['Gillette', 'Wyoming', '32884'],
	['Laramie', 'Wyoming', '31659'],
	['Rock Springs', 'Wyoming', '23196'],
	['Sheridan', 'Wyoming', '19095'],
	['Evanston', 'Wyoming', '11814'],
	['Green River', 'Wyoming', '11609'],
	['Jackson', 'Wyoming', '10849'],
	['Riverton', 'Wyoming', '10587'],
	['Cody', 'Wyoming', '10174'],
	['Rawlins', 'Wyoming', '8298'],
	['Lander', 'Wyoming', '7550'],
	['Powell', 'Wyoming', '6418'],
	['Douglas', 'Wyoming', '6351'],
	['Torrington', 'Wyoming', '6132'],
	['Worland', 'Wyoming', '4787'],
	['Buffalo', 'Wyoming', '4469'],
	['Mills', 'Wyoming', '4221'],
	['Wheatland', 'Wyoming', '3597'],
	['Newcastle', 'Wyoming', '3204'],
	['Bar Nunn', 'Wyoming', '2978'],
	['Evansville', 'Wyoming', '2749'],
	['Thermopolis', 'Wyoming', '2706'],
	['Kemmerer', 'Wyoming', '2422'],
	['Glenrock', 'Wyoming', '2407'],
	['Lovell', 'Wyoming', '2271'],
	['Pinedale', 'Wyoming', '2262'],
	['Afton', 'Wyoming', '2213'],
	['Lyman', 'Wyoming', '2175'],
	['Star Valley Ranch', 'Wyoming', '1967'],
	['Saratoga', 'Wyoming', '1727'],
	['Greybull', 'Wyoming', '1680'],
	['Wright', 'Wyoming', '1619'],
	['Lusk', 'Wyoming', '1497'],
	['Mountain View', 'Wyoming', '1287'],
	['Alpine', 'Wyoming', '1262'],
	['Basin', 'Wyoming', '1231'],
	['Pine Bluffs', 'Wyoming', '1156'],
	['Guernsey', 'Wyoming', '1138'],
	['Ranchester', 'Wyoming', '1110'],
	['Sundance', 'Wyoming', '1043'],
	['Moorcroft', 'Wyoming', '965'],
	['Dubois', 'Wyoming', '919'],
	['Upton', 'Wyoming', '913'],
	['Dayton', 'Wyoming', '828'],
	['Marbleton', 'Wyoming', '810'],
	['Cowley', 'Wyoming', '795'],
	['Hanna', 'Wyoming', '683'],
	['Byron', 'Wyoming', '568'],
	['Diamondville', 'Wyoming', '526'],
	['Bear River', 'Wyoming', '525'],
	['Pine Haven', 'Wyoming', '512'],
	['Cokeville', 'Wyoming', '503'],
	['Shoshoni', 'Wyoming', '491'],
	['Encampment', 'Wyoming', '453'],
	['Hudson', 'Wyoming', '439'],
	['Rolling Hills', 'Wyoming', '422'],
	['Baggs', 'Wyoming', '406'],
	['La Barge', 'Wyoming', '401'],
	['Lingle', 'Wyoming', '400'],
	['Thayne', 'Wyoming', '391'],
	['LaGrange', 'Wyoming', '376'],
	['Sinclair', 'Wyoming', '374'],
	['Big Piney', 'Wyoming', '373'],
	['Burns', 'Wyoming', '372'],
	['Burlington', 'Wyoming', '334'],
	['Hulett', 'Wyoming', '318'],
	['Meeteetse', 'Wyoming', '314'],
	['Midwest', 'Wyoming', '283'],
	['Kaycee', 'Wyoming', '264'],
	['Ten Sleep', 'Wyoming', '251'],
	['Medicine Bow', 'Wyoming', '245'],
	['Glendo', 'Wyoming', '239'],
	['East Thermopolis', 'Wyoming', '226'],
	['Pavillion', 'Wyoming', '226'],
	['Rock River', 'Wyoming', '219'],
	['Fort Laramie', 'Wyoming', '210'],
	['Wamsutter', 'Wyoming', '200'],
	['Superior', 'Wyoming', '182'],
	['Chugwater', 'Wyoming', '178'],
	['Albin', 'Wyoming', '167'],
	['Deaver', 'Wyoming', '156'],
	['Edgerton', 'Wyoming', '153'],
	['Elk Mountain', 'Wyoming', '152'],
	['Frannie', 'Wyoming', '142'],
	['Yoder', 'Wyoming', '133'],
	['Clearmont', 'Wyoming', '119'],
	['Granger', 'Wyoming', '94'],
	['Manville', 'Wyoming', '94'],
	['Manderson', 'Wyoming', '89'],
	['Dixon', 'Wyoming', '77'],
	['Kirby', 'Wyoming', '75'],
	['Bairoil', 'Wyoming', '67'],
	['Hartville', 'Wyoming', '67'],
	['Opal', 'Wyoming', '63'],
	['Riverside', 'Wyoming', '63'],
	['Van Tassell', 'Wyoming', '23'],
	['Lost Springs', 'Wyoming', '4'],
];

export const stateNames = [
	'Alabama',
	'Alaska',
	'AmericanSamoa',
	'Arizona',
	'Arkansas',
	'California',
	'Colorado',
	'Connecticut',
	'Delaware',
	'DistrictOfColumbia',
	'Florida',
	'Georgia',
	'Guam',
	'Hawaii',
	'Idaho',
	'Illinois',
	'Indiana',
	'Iowa',
	'Kansas',
	'Kentucky',
	'Louisiana',
	'Maine',
	'Maryland',
	'Massachusetts',
	'Michigan',
	'Minnesota',
	'Mississippi',
	'Missouri',
	'Montana',
	'Nebraska',
	'Nevada',
	'NewHampshire',
	'NewJersey',
	'NewMexico',
	'NewYork',
	'NorthCarolina',
	'NorthDakota',
	'NorthernMarianaIslands',
	'Ohio',
	'Oklahoma',
	'Oregon',
	'Pennsylvania',
	'PuertoRico',
	'RhodeIsland',
	'SouthCarolina',
	'SouthDakota',
	'Tennessee',
	'Texas',
	'U.S.VirginIslands',
	'Utah',
	'Vermont',
	'Virginia',
	'Washington',
	'WestVirginia',
	'Wisconsin',
	'Wyoming',
];

export const cityNames = [
	'Huntsville',
	'Montgomery',
	'Birmingham',
	'Mobile',
	'Tuscaloosa',
	'Hoover',
	'Auburn',
	'Dothan',
	'Madison',
	'Decatur',
	'Florence',
	'Prattville',
	'Gadsden',
	'Alabaster',
	'Opelika',
	'Northport',
	'Enterprise',
	'Daphne',
	'Athens',
	'Trussville',
	'Homewood',
	'Bessemer',
	'Pelham',
	'Fairhope',
	'Albertville',
	'Oxford',
	'Foley',
	'Helena',
	'Anniston',
	'Prichard',
	'Cullman',
	'Selma',
	'Troy',
	'Calera',
	'Millbrook',
	'Hueytown',
	'Gardendale',
	'Saraland',
	'Chelsea',
	'Scottsboro',
	'Talladega',
	'Hartselle',
	'Jasper',
	'Ozark',
	'Moody',
	'Irondale',
	'Jacksonville',
	'Eufaula',
	'Sylacauga',
	'Leeds',
	'Russellville',
	'Valley',
	'Clay',
	'Boaz',
	'Fairfield',
	'Fultondale',
	'Southside',
	'Sheffield',
	'Tuscumbia',
	'Tuskegee',
	'Clanton',
	'Andalusia',
	'Guntersville',
	'Atmore',
	'Arab',
	'Greenville',
	'Montevallo',
	'Wetumpka',
	'Pinson',
	'Lincoln',
	'Demopolis',
	'Hamilton',
	'Robertsdale',
	'Oneonta',
	'Satsuma',
	'Lanett',
	'Opp',
	'Chickasaw',
	'Tarrant',
	'Monroeville',
	'Attalla',
	'Rainsville',
	'Margaret',
	'Glencoe',
	'Roanoke',
	'Brewton',
	'Semmes',
	'Headland',
	'Midfield',
	'Odenville',
	'Springville',
	'Daleville',
	'Winfield',
	'Piedmont',
	'Tallassee',
	'Childersburg',
	'Jackson',
	'Argo',
	'Haleyville',
	'Adamsville',
	'Columbiana',
	'Fayette',
	'Geneva',
	'Loxley',
];
